---
- hosts: localhost
  gather_facts: no
  tasks:
  - name:
    pip:
      name: boto3
      state: present

  - name: install apache
    apt:
      name: apache2
      state: latest
    become: yes
    
  - name: Copy html file
    ansible.builtin.copy:
      src: ./welcome.html
      dest: /var/www/html/welcome.html
      
  - name: apache2 listen on port 8900 ports.conf
    lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8900" state=present
      
  - name: restart apache2
    service: 
      name: apache2
      state: restarted
